[package]
name = "throttled_xrp_rpc"
version = "0.2.3"
authors = ["Aiden McClelland <aiden.k.mcclelland@gmail.com>", "Drew Ansbacher <drew.ansbacher@gmail.com>"]
repository = "https://github.com/DR-BoneZ/throttled-xrp-rpc-rs"
homepage = "https://github.com/DR-BoneZ/throttled-xrp-rpc-rs"
license = "MIT"
readme = "README.md"
documentation = "http://docs.rs/throttled_xrp_rpc/"
description = "Throttled XRP RPC API client for Rust."
edition = "2018"

[dependencies]
throttled_json_rpc = { version = "0.0.7", git = "https://github.com/SALTLending/throttled-json-rpc-rs"}
failure = "0.1.5"
reqwest = "0.9.20"
serde = { version = "1.0.99", features = ["derive", ] }
serde_json = "1.0.40"
bigdecimal = { version = "0.1.0", features = ["serde"] }

[dev-dependencies]
lazy_static = "1.3.0"
num-traits = "0.2.8"
